window.comassetPortfolio = {
  asOf: "2026-06-17",
  baseCurrency: "USD",
  holdings: [
    {
      ticker: "VTI",
      name: "Vanguard Total Stock Market ETF",
      type: "etf",
      sector: "Broad Market",
      assetClass: "US Equity",
      value: 24000,
      costBasis: 21000,
      weight: 0.32,
      overlapTickers: ["MSFT", "NVDA", "COST", "LLY"],
    },
    {
      ticker: "VFIAX",
      name: "Vanguard 500 Index Fund Admiral Shares",
      type: "fund",
      sector: "Large Cap Blend",
      assetClass: "US Equity",
      value: 18500,
      costBasis: 16400,
      weight: 0.247,
      overlapTickers: ["MSFT", "NVDA", "COST", "LLY"],
    },
    {
      ticker: "MSFT",
      name: "Microsoft Corporation",
      type: "stock",
      sector: "Technology",
      assetClass: "US Equity",
      value: 11200,
      costBasis: 7800,
      weight: 0.149,
      overlapTickers: [],
    },
    {
      ticker: "QQQM",
      name: "Invesco NASDAQ 100 ETF",
      type: "etf",
      sector: "Growth / Technology",
      assetClass: "US Equity",
      value: 8200,
      costBasis: 7600,
      weight: 0.109,
      overlapTickers: ["MSFT", "NVDA"],
    },
    {
      ticker: "SGOV",
      name: "iShares 0-3 Month Treasury Bond ETF",
      type: "etf",
      sector: "Treasury",
      assetClass: "Cash / T-Bills",
      value: 12200,
      costBasis: 12100,
      weight: 0.163,
      overlapTickers: [],
    },
  ],
  targetBands: {
    "US Equity": { min: 0.55, max: 0.78 },
    "Cash / T-Bills": { min: 0.08, max: 0.22 },
  },
};
